-- MySQL Script generated by MySQL Workbench
-- Thu Mar 31 09:50:22 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `city` ;

CREATE TABLE IF NOT EXISTS `city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `phoneNumber` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `address` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image` ;

CREATE TABLE IF NOT EXISTS `image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `link` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `path` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supplier` ;

CREATE TABLE IF NOT EXISTS `supplier` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `presentation` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `phoneNumber` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `address` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer` ;

CREATE TABLE IF NOT EXISTS `offer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `details` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `discountPrice` INT(11) NOT NULL COMMENT '',
  `publicPrice` INT(11) NOT NULL COMMENT '',
  `startDate` DATETIME NOT NULL COMMENT '',
  `endDate` DATETIME NOT NULL COMMENT '',
  `address` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `idSupplier` INT(11) NOT NULL COMMENT '',
  `idCategory` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idSupplier_idx` (`idSupplier` ASC)  COMMENT '',
  INDEX `idCategory_idx` (`idCategory` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_supplier`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_city` ;

CREATE TABLE IF NOT EXISTS `offer_city` (
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idCity` INT(11) NOT NULL COMMENT '',
  INDEX `idOffer_idx` (`idOffer` ASC)  COMMENT '',
  INDEX `idCity_idx` (`idCity` ASC)  COMMENT '',
  PRIMARY KEY (`idOffer`, `idCity`)  COMMENT '',
  CONSTRAINT `fk_offer_city_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_city_city`
    FOREIGN KEY (`idCity`)
    REFERENCES `city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_image` ;

CREATE TABLE IF NOT EXISTS `offer_image` (
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idImage` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idOffer`, `idImage`)  COMMENT '',
  INDEX `idImage_idx` (`idImage` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_image_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_image_image`
    FOREIGN KEY (`idImage`)
    REFERENCES `image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_order` ;

CREATE TABLE IF NOT EXISTS `offer_order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idCustomer` INT(11) NOT NULL COMMENT '',
  `quantity` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idOffer_idx` (`idOffer` ASC)  COMMENT '',
  INDEX `idCustomer_idx` (`idCustomer` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_order_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_order_customer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sub_category` ;

CREATE TABLE IF NOT EXISTS `sub_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `idCategory` INT(11) NOT NULL COMMENT '',
  INDEX `idCategory_idx` (`idCategory` ASC)  COMMENT '',
  PRIMARY KEY (`id`, `idCategory`)  COMMENT '',
  CONSTRAINT `fk_sub_category_category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_sub_category` ;

CREATE TABLE IF NOT EXISTS `offer_sub_category` (
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idSubCategory` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idOffer`, `idSubCategory`)  COMMENT '',
  INDEX `idSubCategory_idx` (`idSubCategory` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_sub_category_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_sub_category_sub_category`
    FOREIGN KEY (`idSubCategory`)
    REFERENCES `sub_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tag` ;

CREATE TABLE IF NOT EXISTS `tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_tag` ;

CREATE TABLE IF NOT EXISTS `offer_tag` (
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idTag` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idOffer`, `idTag`)  COMMENT '',
  INDEX `idTag_idx` (`idTag` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_tag_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_tag_tag`
    FOREIGN KEY (`idTag`)
    REFERENCES `tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `offer_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `offer_view` ;

CREATE TABLE IF NOT EXISTS `offer_view` (
  `idOffer` INT(11) NOT NULL COMMENT '',
  `idCustomer` INT(11) NULL COMMENT '',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  INDEX `idOffer_idx` (`idOffer` ASC)  COMMENT '',
  INDEX `idCustomer_idx` (`idCustomer` ASC)  COMMENT '',
  CONSTRAINT `fk_offer_view_offer`
    FOREIGN KEY (`idOffer`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_view_customer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
